### ISSUE TITLE
Timeout error

### ISSUE THREAD

**Issue by skeggse** [mixmaxhq/erik#14] opened 2017-07-05 23:52 UTC
We're seeing an issue with Erik or Karma or PhantomJS - it looks like the tests run correctly, but Karma never gets the message, leading to a timeout error.

```
[ ... ]

SUMMARY:

* 242 tests completed

[23:15:38] Finished 'erik-run-spec' after 1.05 s
[23:15:38] Finished 'erik' after 16 s

05 07 2017 23:15:48.564:WARN [PhantomJS 2.1.1 (Linux 0.0.0)]: Disconnected (1 times), because no message in 10000 ms.

PhantomJS 2.1.1 (Linux 0.0.0) ERROR

  Disconnected, because no message in 10000 ms.

Finished in 10.532 secs / 0.187 secs @ 23:15:48 GMT+0000 (UTC)

[23:15:48] 'erik-run-spec' errored after 11 s
[23:15:48] Error: Karma returned with the exit code: 1
    at /home/travis/build/.../node_modules/erik/index.js:155:19
    at removeAllListeners (/home/travis/build/.../node_modules/karma/lib/server.js:380:7)
    at /home/travis/build/.../node_modules/karma/lib/server.js:391:9
    at Server.<anonymous> (net.js:1507:9)
    at Server.g (events.js:291:16)
    at emitNone (events.js:86:13)
    at Server.emit (events.js:185:7)
    at emitCloseNT (net.js:1553:8)
    at _combinedTickCallback (internal/process/next_tick.js:71:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
```

**Comment by spencer-brown** [comment] 2017-07-21 01:03
looks like this is a long-standing issue with karma and/or phantomjs. the issue is tracked [here](https://github.com/karma-runner/karma-phantomjs-launcher/issues/1260) with no real solution. config changes seem to randomly solve this issue for people.

**Comment by spencer-brown** [comment] 2017-07-21 18:27
fixed with https://github.com/mixmaxhq/erik/pull/18

**Closed by spencer-brown** 2017-07-21 18:27 UTC
